#!/usr/bin/env bash
# slim uses exec /bin/bash -login ~/.xinitrc %session
# so bash is started as a non interactive login shell.
# bash will only search for ~/.bash_profile, ~/.bash_login, or ~/.profile
# The interpreter of this script is then a non interactive shell,
# reading only $ZDOTDIR/.zshenv (if zsh) or $BASH_ENV (if bash)

# my logs have nothing to do in /var/log/slim.log
exec >> .session.log 2>> .session.err
# broadcast the date in the log files
echo      "xinitrc : `date`"
echo 1>&2 "xinitrc : `date`"

# before starting xmonad, we want a correct X db and a running urxvt daemon
xrdb -merge ~/.Xresources
urxvtd -q -f -o

nitrogen --restore &

xsetroot -cursor_name left_ptr &
statusbar start &
xmonad & wmpid=$!

resetxkbmap

xscreensaver -no-splash &

# terminus is in /usr/share/fonts/local/
[ -d /usr/share/fonts/local/ ] && xset +fp /usr/share/fonts/local/ && xset fp rehash

wait $wmpid # like exec myWM but more flexible

keychain --stop all
# pkill -HUP ssh-agent
